// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app2;

#nullable disable

namespace app2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015094714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("app2.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime")
                        .HasColumnName("create_time");

                    b.Property<bool>("is_delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_delete");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<DateTime>("update_time")
                        .HasColumnType("datetime")
                        .HasColumnName("update_time");

                    b.HasKey("id");

                    b.HasIndex("is_delete")
                        .HasDatabaseName("idx_user_is_delete");

                    b.HasIndex("name")
                        .HasDatabaseName("idx_user_name");

                    b.HasIndex("name", "is_delete")
                        .HasDatabaseName("idx_user_name_is_delete");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
